"""
Aegis — incident-report email (Phase 2).

Two real send paths, chosen by what's configured (never a fake "sent"):

    1. Resend API   — used when RESEND_API_KEY is set (the primary path).
    2. SMTP         — fallback when SMTP_HOST + SMTP_USER + SMTP_PASS are set.

If NEITHER is configured we raise ``EmailNotConfigured`` with a clear message
listing exactly which env vars to set. Callers surface that honestly rather
than pretending the report went out.

Recipients: ``EMAIL_TO`` (comma-separated) unless an explicit list is passed.
Sender: ``EMAIL_FROM``. Nothing here ever prints a key.
"""
from __future__ import annotations

import os
import smtplib
import ssl
from email.message import EmailMessage
from typing import Optional


class EmailNotConfigured(RuntimeError):
    """No Resend key and no SMTP credentials present."""


class EmailError(RuntimeError):
    """A configured provider was reached but the send failed."""


def _recipients(to: Optional[list[str]]) -> list[str]:
    if to:
        return to
    raw = os.getenv("EMAIL_TO", "")
    return [a.strip() for a in raw.split(",") if a.strip()]


def is_configured() -> bool:
    if os.getenv("RESEND_API_KEY"):
        return True
    return bool(os.getenv("SMTP_HOST") and os.getenv("SMTP_USER") and os.getenv("SMTP_PASS"))


# --------------------------------------------------------------------------- #
# Report rendering
# --------------------------------------------------------------------------- #
def build_incident_report(run: dict) -> tuple[str, str, str]:
    """Return (subject, plain_text, html) for a persisted/finished incident run."""
    v = run.get("verdict") or {}
    pm = run.get("postmortem") or {}
    service = run.get("service") or "service"
    region = run.get("region") or "—"
    resolved = bool(v.get("resolved"))
    inc_id = pm.get("incident_id") or run.get("incident_id") or "INCIDENT"

    subject = f"[Aegis] {inc_id} — {service}/{region} {'RESOLVED' if resolved else 'ESCALATED'}"

    mttr = v.get("mttr_seconds") or pm.get("mttr_seconds") or 0
    lines = [
        f"Incident: {inc_id} — {pm.get('title', service)}",
        f"Severity: {run.get('severity', 'SEV1')}",
        f"Status:   {'RESOLVED' if resolved else 'ESCALATED TO HUMAN'}",
        "",
        f"Root cause: {pm.get('root_cause', 'n/a')}",
        f"Resolution: {pm.get('resolution', v.get('action', 'n/a'))}",
        f"Approved by: {v.get('approved_by', 'n/a')}",
        "",
        f"MTTR: {mttr/60:.1f} min ({mttr:.0f}s)",
        f"Downtime cost: ${v.get('downtime_cost_usd', 0):,.0f}",
        f"Remediation cost: ${v.get('remediation_cost_usd', 0):,.0f}",
        f"Cost averted vs manual: ${v.get('averted_cost_usd', 0):,.0f}",
        "",
        "Cost summary: " + (pm.get("cost_summary", "n/a")),
        "",
        "Follow-ups:",
    ]
    for f in pm.get("follow_ups", []) or ["(none recorded)"]:
        lines.append(f"  - {f}")
    if pm.get("timeline"):
        lines += ["", "Timeline:"]
        lines += [f"  {t}" for t in pm["timeline"]]
    text = "\n".join(lines)

    fu_html = "".join(f"<li>{f}</li>" for f in (pm.get("follow_ups") or []))
    tl_html = "".join(f"<li>{t}</li>" for t in (pm.get("timeline") or []))
    html = f"""\
<div style="font-family:ui-monospace,Menlo,monospace;max-width:640px;color:#0a0e17">
  <h2 style="margin:0 0 4px">{inc_id} — {service}/{region}</h2>
  <p style="color:{'#0a8a4f' if resolved else '#b4232a'};font-weight:700;margin:0 0 12px">
    {'RESOLVED' if resolved else 'ESCALATED TO HUMAN'}</p>
  <p><b>Root cause:</b> {pm.get('root_cause', 'n/a')}<br>
     <b>Resolution:</b> {pm.get('resolution', v.get('action', 'n/a'))}<br>
     <b>Approved by:</b> {v.get('approved_by', 'n/a')}</p>
  <table cellpadding="6" style="border-collapse:collapse;background:#f4f6fb">
    <tr><td><b>MTTR</b></td><td>{mttr/60:.1f} min</td></tr>
    <tr><td><b>Downtime cost</b></td><td>${v.get('downtime_cost_usd', 0):,.0f}</td></tr>
    <tr><td><b>Remediation cost</b></td><td>${v.get('remediation_cost_usd', 0):,.0f}</td></tr>
    <tr><td><b>Cost averted</b></td><td>${v.get('averted_cost_usd', 0):,.0f}</td></tr>
  </table>
  <h3>Follow-ups</h3><ul>{fu_html or '<li>(none)</li>'}</ul>
  {'<h3>Timeline</h3><ul>' + tl_html + '</ul>' if tl_html else ''}
  <p style="color:#8092ad;font-size:12px">Generated by Aegis.</p>
</div>"""
    return subject, text, html


# --------------------------------------------------------------------------- #
# Send
# --------------------------------------------------------------------------- #
def send_email(subject: str, text: str, html: str, to: Optional[list[str]] = None) -> dict:
    """Send via Resend (preferred) or SMTP. Raises if nothing is configured."""
    recipients = _recipients(to)
    sender = os.getenv("EMAIL_FROM")
    if not is_configured():
        raise EmailNotConfigured(
            "Email not configured. Set RESEND_API_KEY (+ EMAIL_FROM/EMAIL_TO) for "
            "the Resend path, or SMTP_HOST/SMTP_USER/SMTP_PASS (+ EMAIL_FROM/EMAIL_TO)."
        )
    if not sender:
        raise EmailNotConfigured("EMAIL_FROM is not set.")
    if not recipients:
        raise EmailNotConfigured("No recipients: set EMAIL_TO or pass an explicit list.")

    if os.getenv("RESEND_API_KEY"):
        return _send_resend(sender, recipients, subject, text, html)
    return _send_smtp(sender, recipients, subject, text, html)


def _send_resend(sender: str, to: list[str], subject: str, text: str, html: str) -> dict:
    import httpx
    try:
        resp = httpx.post(
            "https://api.resend.com/emails",
            headers={"Authorization": f"Bearer {os.environ['RESEND_API_KEY']}"},
            json={"from": sender, "to": to, "subject": subject, "text": text, "html": html},
            timeout=30.0,
        )
        resp.raise_for_status()
        return {"provider": "resend", "status": "sent", "to": to, "id": resp.json().get("id")}
    except httpx.HTTPStatusError as e:
        raise EmailError(f"Resend rejected the send: {e.response.status_code} {e.response.text}") from e
    except httpx.HTTPError as e:
        raise EmailError(f"Resend request failed: {e}") from e


def _send_smtp(sender: str, to: list[str], subject: str, text: str, html: str) -> dict:
    msg = EmailMessage()
    msg["From"], msg["To"], msg["Subject"] = sender, ", ".join(to), subject
    msg.set_content(text)
    msg.add_alternative(html, subtype="html")
    host = os.environ["SMTP_HOST"]
    port = int(os.getenv("SMTP_PORT", "587"))
    try:
        with smtplib.SMTP(host, port, timeout=30) as smtp:
            smtp.starttls(context=ssl.create_default_context())
            smtp.login(os.environ["SMTP_USER"], os.environ["SMTP_PASS"])
            smtp.send_message(msg)
        return {"provider": "smtp", "status": "sent", "to": to}
    except (smtplib.SMTPException, OSError) as e:
        raise EmailError(f"SMTP send failed via {host}:{port}: {e}") from e


def send_incident_report(run: dict, to: Optional[list[str]] = None) -> dict:
    subject, text, html = build_incident_report(run)
    return send_email(subject, text, html, to)
