"""
Capture a FAITHFUL transcript of the real offline engine for client-side demo
playback. Runs the same deterministic cascade as `python -m backend.run` and
writes the exact ordered messages + verdict to the frontend bundle.

    python scripts/capture_demo.py

Outputs (regenerate whenever the engine changes — never hand-edit):
    frontend/static/demo_run.json   the faithful artifact
    frontend/static/demo_run.js     window.DEMO_RUN = <same data>  (zero-fetch load)
"""
from __future__ import annotations

import asyncio
import json
import time
from pathlib import Path

import backend  # noqa: F401  (autoloads .env; harmless offline)
from backend.orchestrator import run_incident

STATIC = Path(__file__).resolve().parent.parent / "frontend" / "static"


async def main() -> None:
    posted, verdict = await run_incident()           # the real engine, offline
    data = {
        "source": "python -m backend.run (offline, deterministic)",
        "captured_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
        "messages": [m.model_dump(mode="json") for m in posted],
        "verdict": verdict,
    }
    (STATIC / "demo_run.json").write_text(json.dumps(data, indent=2), encoding="utf-8")
    (STATIC / "demo_run.js").write_text(
        "/* AUTO-GENERATED by scripts/capture_demo.py — do not edit by hand. */\n"
        "window.DEMO_RUN = " + json.dumps(data, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    print(f"captured {len(data['messages'])} messages; "
          f"verdict: {verdict['action']} MTTR {verdict['mttr_seconds']:.0f}s "
          f"averted ${verdict['averted_cost_usd']:,.0f}")


if __name__ == "__main__":
    asyncio.run(main())
